[package]
name = "autoit_wrapper"
version = "0.1.0"
edition = "2021"
keywords = ["autoit3", "autoitx"]

[dependencies]
libloading = "0.8"
lazy_static = "1.5"
 
[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation"
]

